fix

diff --git a/.github/actions/regression-tests/action.yml b/.github/actions/regression-tests/action.yml
--- a/.github/actions/regression-tests/action.yml
+++ b/.github/actions/regression-tests/action.yml
@@ -25,19 +25,19 @@ runs:
   # bring back timeouts once composite actions start supporting them
   # timeout-minutes: 20
   steps:
-    #    - name: Run PyTests
-    #      id: first
-    #      shell: bash
-    #      run: |
-    #        ls -l ${GITHUB_WORKSPACE}/
-    #        cd ${GITHUB_WORKSPACE}/tests
-    #        echo "Current commit is ${{github.sha}}"
-    #        pip3 install -r dragonfly/requirements.txt
-    #        # used by PyTests
-    #        export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/${{inputs.build-folder-name}}/${{inputs.dfly-executable}}"
-    #        export UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 # to crash on errors
-    #
-    #        timeout 20m pytest -m "${{inputs.filter}}" --json-report --json-report-file=report.json dragonfly --ignore=dragonfly/replication_test.py --log-cli-level=INFO || code=$?; if [[ $code -eq 124 ]]; then echo "TIMEDOUT=1">> "$GITHUB_OUTPUT"; exit 1; fi
+    - name: Run PyTests
+      id: first
+      shell: bash
+      run: |
+        ls -l ${GITHUB_WORKSPACE}/
+        cd ${GITHUB_WORKSPACE}/tests
+        echo "Current commit is ${{github.sha}}"
+        pip3 install -r dragonfly/requirements.txt
+        # used by PyTests
+        export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/${{inputs.build-folder-name}}/${{inputs.dfly-executable}}"
+        export UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 # to crash on errors
+
+        #timeout 20m pytest -m "${{inputs.filter}}" --json-report --json-report-file=report.json dragonfly --ignore=dragonfly/replication_test.py --log-cli-level=INFO || code=$?; if [[ $code -eq 124 ]]; then echo "TIMEDOUT=1">> "$GITHUB_OUTPUT"; exit 1; fi
     #
     - name: Run PyTests replication test
       id: second
