feat server: remove multi shard sync from replication
Signed-off-by: adi_holden <adi@dragonflydb.io>

diff --git a/.github/actions/regression-tests/action.yml b/.github/actions/regression-tests/action.yml
--- a/.github/actions/regression-tests/action.yml
+++ b/.github/actions/regression-tests/action.yml
@@ -60,25 +60,21 @@ runs:
         # used by PyTests
         export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/${{inputs.build-folder-name}}/${{inputs.dfly-executable}}"
 
-        run_pytest_with_args() {
-          timeout 20m pytest -m "${{inputs.filter}}" --durations=10 --color=yes --json-report \
-            --json-report-file=rep1_report.json dragonfly/replication_test.py --log-cli-level=INFO \
-            --df alsologtostderr $1 $2 || code=$?
 
-          # timeout returns 124 if we exceeded the timeout duration
-          if [[ $code -eq 124 ]]; then
-            echo "TIMEDOUT=1">> "$GITHUB_OUTPUT"
-            exit 1
-          fi
+        timeout 20m pytest -m "${{inputs.filter}}" --durations=10 --color=yes --json-report \
+          --json-report-file=rep1_report.json dragonfly/replication_test.py --log-cli-level=INFO \
+          --df alsologtostderr $1 $2 || code=$?
 
-          # when a test fails in pytest it returns 1 but there are other return codes as well so we just check if the code is non zero
-          if [[ $code -ne 0 ]]; then
-            exit 1
-          fi
-        }
+        # timeout returns 124 if we exceeded the timeout duration
+        if [[ $code -eq 124 ]]; then
+          echo "TIMEDOUT=1">> "$GITHUB_OUTPUT"
+          exit 1
+        fi
 
-        (run_pytest_with_args --df enable_multi_shard_sync=true)
-        (run_pytest_with_args --df enable_multi_shard_sync=false)
+        # when a test fails in pytest it returns 1 but there are other return codes as well so we just check if the code is non zero
+        if [[ $code -ne 0 ]]; then
+          exit 1
+        fi
 
     - name: Print last log on timeout
       if: failure()
